import {getCidades} from '../services/cidade-service'
import {comprovarLogin} from '../services/login-service'
import {getTodosTiposUsuario} from '../services/tipoUsuario-get-service'
import {atualizarUsuarioService} from '../services/usuario-atualizar-service'
import {deletarUsuarioService} from '../services/usuario-deletar-service'
import {getTodosUsuariosFiltrados} from '../services/usuario-get-filtrado-service'
import {getTodosUsuarios} from '../services/usuario-get-service'
import {getVerificarTipoUsuario} from '../services/usuario-get-verificar-tipo-service'
import {getDadosUsuarioLogado} from '../services/usuario-logado-get'
import {salvarUsuario} from '../services/usuario-salvar-service'

